Qase feature property driver
Bivis-s/EDU-AQA-Qase pull request #2
Opened 2021-03-09 16:42 UTC by Bivis-s

Now you can create PropertyDriver, which creates WebDriver proxy by driver.properties file 
![image](https://user-images.githubusercontent.com/66497536/110505700-75749800-810f-11eb-92d5-a8712653a63c.png)

Also added LoginPage and started to add ProjectsPage

2021-03-10 11:33 UTC, Bivis-s commented
### Started to work in another branch.

2021-03-10 20:21 UTC, vchesnakoutest requested changes
please make fixes

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/pageobjects/HomePage.java
>      public HomePage isLoaded() throws Error {
если есть try / catch то  throws Error тут уже не нужен

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/pageobjects/HomePage.java
> +        } catch (Error e) {
и тут лучше ловить не Error, а какой-то конкретный эксепшн (и во всех остальных местах тоже)

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/helpers/ElementsManipulator.java
> +            PageLoadHelper.waitFor(getDriver(), ExpectedConditions.visibilityOf(element));
waitFor -> лучше назвать waitForCondition

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/pageobjects/HomePage.java
>      public HomePage isLoaded() throws Error {
waitForPageIsLoaded

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/pageobjects/HomePage.java
>      private static final String SIGN_IN_BUTTON_ID = "signin";
если используешь во всем фреймворке PageFactory, то тут тоже его надо использовать (@FindBy)

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/pageobjects/ProjectsPage.java
> +    private static final String CREATE_NEW_PROJECT_BUTTON_ID = "createButton";
тоже findby

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/setups/DriverPropertyFactory.java
> +        FIREFOX("firefox");
enums желательно описывать в отдельном классе

2021-03-10 20:21 UTC, vchesnakoutest commented on src/main/java/utils/readers/UrlPropertyReader.java
> +        PROJECTS("projects");
тоже лучше в отдельном классе описывать

2021-03-10 22:52 UTC, Bivis-s commented on src/main/java/pageobjects/HomePage.java
>      private static final String SIGN_IN_BUTTON_ID = "signin";
Решил обойтись без PageFactory

2021-03-10 22:54 UTC, Bivis-s commented on src/main/java/setups/DriverPropertyFactory.java
> +        FIREFOX("firefox");
вынесу

2021-03-10 22:54 UTC, Bivis-s commented on src/main/java/utils/readers/UrlPropertyReader.java
> +        PROJECTS("projects");
вынесу

2021-03-10 22:54 UTC, Bivis-s commented on src/main/java/pageobjects/ProjectsPage.java
> +    private static final String CREATE_NEW_PROJECT_BUTTON_ID = "createButton";
так и оставим

2021-03-10 22:56 UTC, Bivis-s commented on src/main/java/helpers/ElementsManipulator.java
> +            PageLoadHelper.waitFor(getDriver(), ExpectedConditions.visibilityOf(element));
переименую

2021-03-10 23:25 UTC, Bivis-s commented on src/main/java/pageobjects/HomePage.java
>      public HomePage isLoaded() throws Error {
да, уберу, вообще лучше не указывать throws в сигнатуре метода, если это возможно (Error как раз unchecked throwable)

2021-03-11 15:09 UTC, Bivis-s commented on src/main/java/pageobjects/HomePage.java
>      public HomePage isLoaded() throws Error {
Этот метод наследуется от моего самописного LoadableComponent
![image](https://user-images.githubusercontent.com/66497536/110807935-95819400-8294-11eb-9ea8-26f7113aaa0d.png)

В селениуме есть встроенное решение, где этот метот называется так же как и мой

2021-03-11 15:13 UTC, vchesnakoutest requested changes

2021-03-11 15:13 UTC, vchesnakoutest commented on src/main/java/element_decorators/InputForm.java
> +    public void sendKeys(String... keys) {
добавь аннотацию @Override

2021-03-11 15:13 UTC, vchesnakoutest commented on src/main/java/pageobjects/HomePage.java
> +    public HomePage isLoaded() {
waitForPageIsLoaded или что-то похожее

2021-03-11 16:00 UTC, merged